# Generated by Django 3.0.5 on 2021-09-18 08:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hobby', models.CharField(max_length=50, verbose_name='pasa tiempo')),
            ],
            options={
                'verbose_name': 'hobby',
                'verbose_name_plural': 'hobbies',
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hora', models.TimeField(verbose_name='hora')),
                ('asunto', models.CharField(max_length=100, verbose_name='asunto de reunión')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Person')),
            ],
            options={
                'verbose_name': 'reunion',
                'verbose_name_plural': 'reuniones',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=models.ManyToManyField(to='persona.Hobby'),
        ),
    ]
