# Generated by Django 3.2.6 on 2021-09-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='seudonimo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='seudonimo'),
        ),
    ]
