# Generated by Django 3.2.7 on 2021-09-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apelldios',
            field=models.CharField(blank=True, max_length=30, verbose_name='apelldios'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombres',
            field=models.CharField(blank=True, max_length=30, verbose_name='nombres'),
        ),
    ]
