# Generated by Django 3.2.7 on 2021-09-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apelldios',
            new_name='apellidos',
        ),
    ]
